spring:
  servlet:
    multipart:
      max-file-size: 10MB
  redis:
    host: # your redis host
    port: 6379
    database: 1
    jedis:
      pool:
        max-idle: 10
        min-idle: 5
        max-active: 100
        max-wait: 3000
    password: # your redis pwd
  datasource:
    username: # database account
    password: # database pwd
    url: # database url
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080
